### ISSUE TITLE
ClassNotFoundException after multidex enabled

### ISSUE THREAD

**Issue by keyuraashra** [timrae/custom-class-loader#1]
Hello Tim,

I am following your code to understand few things and I am in need to of some help from your end, that is why I created the comment here.

I have library project in which I am facing issue of famous 65 K method. What I did so far is, I have enabled multidex for the project other stuff mentioned in the documentation. As its library project I am not having Application class, and I am using AAR file to utilize it in another android project (my main project).

Now I have few queries here which I am sure you can guide me better :-

1) Do I need to add multidex in both project - library as well as main android project? Currently What I did is I enable multi-dex in both as well as I have added Application class which extends MultiDexApplication in my main android project.

2) As of now I am getting class not found exception - I can see 2 .dex file generated in my main project dex folder. 

Can you please kindly guide me the right direction for this as I am not expert in gradle and i am facing the issue since very long time.

**Comment by timrae** [comment]
Hi sorry this project is completely unrelated to the 65K issue... I'm afraid I can't help with your problems
